name 'neo4j'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures neo4j'
long_description 'Installs/Configures neo4j'
version '0.1.0'

depends 'java'
depends 'apt'
